name: PHP Workflow

on: push

jobs:
  test:
    name: PHP Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install
    - name: Run GrumPHP
      run: vendor/bin/grumphp/
